### ISSUE TITLE
has no cancel  list commands

### ISSUE THREAD

**Issue by zhangzhangwenwen** [ocavue/prosemirror-flat-list#148]

**Comment by ocavue** [comment]
Sorry I don't understand this issue. Could you give more details?

**Comment by zhangzhangwenwen** [comment]
the command  that i can toggle a list

**Comment by zhangzhangwenwen** [comment]
"I can use the `createWrapInListCommand` function to convert a piece of content into a list, but I'm unable to revert the list back to its original content."
