### ISSUE TITLE
Allow schema customization?

### ISSUE THREAD

**Issue by intaek-h** [ocavue/prosemirror-flat-list#165]
first of all, i really want to appreciate your hard work on this project. this is amazing considering that the old list plugin is not working fluently.

i just wanted to ask you if you have plans to allow users to customize node spec for list nodes. it's because i give my own classes for all nodes and marks of my editor schema and flat-list seems to not support the feature yet.

**Comment by ocavue** [comment]
Thanks for your kind words.

You can use customize the node spec by wrapping the `createListSpec` API. Here is an example:


```ts
import { createListSpec } from 'prosemirror-flat-list'

function createCustomListSpec() {
  const spec = createListSpec()
  return {
    ...spec,
    attrs: { ...spec.attrs, color: { "default": "red" } }
    toDOM: (node) => {
      let domArray = spec.toDOM(node)
      let domAttrs = domSpec[1]
      if (typeof domAttrs === 'object') {
        domAttrs['data-list-color'] = node.attrs.color
      }
    }
  }
}
```

Hope this helps.

**Comment by intaek-h** [comment]
thank you very much. i will try it ^_^

**Comment by intaek-h** [comment]
@ocavue just one more question. can i opt out of some kinds, when creating the spec?
i only want to apply the ordered, and bullet kind.
i know i can do that using your example but just wanted to know if there's an option!

**Comment by ocavue** [comment]
There is no an option to override `kind`.

**Comment by ocavue** [comment]
Closing this, as it seems no action is required.
