### ISSUE TITLE
Customizing sequential numbering for an ordered list. How can it be done?

### ISSUE THREAD

**Issue by zhangzhangwenwen** [ocavue/prosemirror-flat-list#170]
What are some effective methods for generating sequential numbering for a ordered list through calculations?

**Comment by ocavue** [comment]
In `prosemirror-flat-list`, sequential numbers in an ordered list are generated by using CSS `counter-*` rules. You can override such a number by typing a number larger than one followed by a period and a space (`. `). 



https://github.com/ocavue/prosemirror-flat-list/assets/24715727/26df11ab-a4f1-421b-8c11-049e30eb1fd5
