### ISSUE TITLE
Issue with Transforming First-Line Node into ProseMirror-Flat-List in Embedded Editor Node

### ISSUE THREAD

**Issue by dwzkit** [ocavue/prosemirror-flat-list#200]
## Description:
I am encountering an issue with my implementation of a custom node view in ProseMirror, named embedded_editor_node. Specifically, when attempting to transform the first line within this embedded editor node into a node of type prosemirror-flat-list, the transformation fails. However, transforming this first paragraph into other node types, such as a heading, works without any issues.

## Steps to Reproduce:

1. Create an embedded_editor_node using ProseMirror's NodeView.
2. Try to transform the first paragraph within this node into a prosemirror-flat-list node.

## Expected Behavior:
The first paragraph should successfully transform into a prosemirror-flat-list node.

## Actual Behavior:
The transformation to a prosemirror-flat-list node fails. This is evident in the EmbeddedEditorNodeView's dispatchInner method. When attempting the transformation, the following console log statement returns null:
`console.log('steps[j].map(offsetMap)', steps[j].map(offsetMap));. `
This indicates the transformation does not occur. In contrast, transforming to a heading node works correctly, as the same console log statement does not return null.

## Screenshots:

1. [Insert screenshot showing the failure when transforming into a prosemirror-flat-list node]
![20240127171956_rec_](https://github.com/ocavue/prosemirror-flat-list/assets/41875799/e69d427d-1398-4312-87f7-6276d1487854)

2. [Insert screenshot showing successful transformation into a heading node]
![20240127171922_rec_](https://github.com/ocavue/prosemirror-flat-list/assets/41875799/48eddd64-a2e4-4e64-8c4e-3ce773df6277)

## Code for Reference:

[    [Provide a link to the source code or a relevant excerpt]](https://stackblitz.com/edit/vitejs-vite-pwh5gz?file=main.js)

## Additional Context:
I have conducted some preliminary analysis but am currently unsure of how to resolve this issue. Any insights or suggestions for debugging this problem would be greatly appreciated.

**Comment by ocavue** [comment]
This seems to be a bug from the upstream `prosemirror-transform`. I've submitted a PR to the upstream to fix it. https://github.com/ProseMirror/prosemirror-transform/pull/27

**Comment by ocavue** [comment]
Closed as it's resolved in the `prosemirror-transform`. Although the new version of `prosemirror-transform` has not been released yet, you can use https://github.com/ds300/patch-package or something like it to use the latest code.
