### ISSUE TITLE
bug: Chrome's counters in ordered lists not in sync 

### ISSUE THREAD

**Issue by TeemuKoivisto** [ocavue/prosemirror-flat-list#23]
Hey,

so I noticed the start counters don't always stay in sync:

https://user-images.githubusercontent.com/10279942/218972777-c34e2ab7-2dae-4cbc-bbf7-ade32e434edd.mov

**Comment by ocavue** [comment]
https://user-images.githubusercontent.com/24715727/219040457-a202b675-82f2-4dfb-8a07-5c9b67f68ad1.mp4

It seems that Chrome has bug for `counter-reset` CSS rule. The counter before `C.C` sometimes become incorrect in the video above. This could be a tricky bug.

**Comment by ocavue** [comment]
This is indeed a Chrome bug. I can [reproduce](https://gist.github.com/ocavue/ebee9963dbff92b8c223aa7711346be2) it without ProseMirror. 

I'll try to find a workaround for it.

**Comment by TeemuKoivisto** [comment]
Huh, well that's something. I think you should just wait until it's fixed. Maybe this is related https://bugs.chromium.org/p/chromium/issues/detail?id=1408703&q=counter-reset&can=2

**Comment by ocavue** [comment]
I'll wait for now since I couldn't find any workaround after some quick tries.

**Comment by zhangzhangwenwen** [comment]
has any way to solve
